### PR TITLE
[Feature] Fill advertisement identifier

### PR DESCRIPTION
**Pull request by miquelalvarado**
Since iOS 14, IDFA is available only after a user's explicit acceptance. That's why Segment SDK is no longer using `SEGIDFA()` method but providing a `SEGAdSupportBlock` to provide whatever identifier we want to use as the advertising identifier. This PR propose some necessary changes to adapt the MCVID middleware to these changes. In addition, we provide also the capability to configure SEGMCVIDTracker to generate the MCVID locally instead of having to make a remote request to get it.

### CODE REVIEW

**Comment by xavierjurado** [comment]
cc @bsneed

**Review by bsneed — APPROVED** [review]

**Comment by bsneed** [comment]
Thanks @miquelalvarado @xavierjurado !

It'll probably be later in the week before I can do a pod release.  Are you guys ok with pointing to master in the meantime?

**Comment by xavierjurado** [comment]
Sure, no problem. Thanks @bsneed !

**Comment by xavierjurado** [comment]
Hey @bsneed, any chance we could have the update this week? Thanks!

**Comment by xavierjurado** [comment]
Woah, I just saw you recently renamed "Analytics" to "Segment", so you'll need to change all the imports before we can use 4.1 here. I see you are doing lots of changes in https://github.com/segment-integrations/ as well 👀

**Comment by bsneed** [comment]
@xavierjurado definitely!  I'll push a release out of this later today or early tomorrow. :highfive:

**Comment by xavierjurado** [comment]
Thanks! Oh and congrats on the release of all features announced yesterday! Edge functions look great :)

**Comment by bsneed** [comment]
@xavierjurado thanks so much!!  Edge Functions is pretty awesome.  Let me know if you guys would like to get in on the preview.  Either way, just pushed out v1.2.4 of this library.  Thanks again for all your contributions!

**Comment by xavierjurado** [comment]
We'd love to check it out, I believe it could make our lives much easier 😄

**Pull request merged**
