### PR TITLE
[Feature] Authenticated flag

### PR DESCRIPTION
**Pull request by xavierjurado**
Adobe Audience Manager needs to know the auth state of a user in order for certain segmentation features to work properly. While this is not needed for the standard id-sync call performed with the advertising identifier, it is required when invoking the `syncIntegrationCode` for identifying logged in users.

For this reason I've added an additional parameter to `syncIntegrationCode` to define the authentication state of the user.

* [Visitor Auth States in Audience Manager](https://docs.adobe.com/content/help/en/audience-manager/user-guide/reference/visitor-authentication-states.html)

⚠️ 95% of the changes in this PR are just the aftermath of invoking `pod install`, I've added less than 40 lines of code without any breaking change on the public API 😄

### CODE REVIEW

**Comment by xavierjurado** [comment]
cc @bsneed

**Comment by bsneed** [comment]
@xavierjurado lol @ what pod install did to you. :D

**Comment by bsneed** [comment]
Oops, hit the wrong button.  Merged now.  Release coming shortly.

**Comment by bsneed** [comment]
1.2.3 released. cc @xavierjurado

**Comment by xavierjurado** [comment]
Much appreciated @bsneed 🙇

**Pull request merged**
